var firstName = "Michael";
var lastName = "Jezegou";
var age = 34;
var address = "123 Fake Street";
var dateOfBirth = "03/05/1985";
console.log(firstName);
console.log(lastName);
console.log(age);
console.log(address);
console.log(dateOfBirth);