var firstName = "Michael";
var lastName = "Jezegou";
var age = 34;
var address = "123 Fake Street";
var dateOfBirth = "03/05/1985";
console.log("First Name: ", firstName);
console.log("Last Name ", lastName);
console.log("Age: ", age);
console.log("Address: ", address);
console.log("Date of Birth: ", dateOfBirth);