let iceCreamFlavors = ["chocolate", "vanilla", "strawberry", "mint", "aftereight", "junior", "candy cane", "thin", "cherry", "cinnamon"];
let iceCreamFlavorsOne = iceCreamFlavors.pop();
let iceCreamFlavorsTwo = iceCreamFlavors.pop();
let iceCreamFlavorsThree = iceCreamFlavors.pop();
let iceCreamFlavorsFour = iceCreamFlavors.pop();
console.log(iceCreamFlavors);
console.log("First removed " + iceCreamFlavorsOne);
console.log("Second removed " + iceCreamFlavorsTwo);
console.log("Third removed " + iceCreamFlavorsThree);
console.log("Fourth removed " + iceCreamFlavorsFour);